### ISSUE TITLE
Change card position

### ISSUE THREAD

**Issue by cloudstudio** [awesome-nova/filter-card#2]
Hello ! are you open to PR ? could be nice do something like this, just inside table.

I think is more usable / beautiful.

![order](https://user-images.githubusercontent.com/3589377/56513397-a6a34980-6532-11e9-9eec-8a18387a9cf3.png)

**Comment by dkulyk** [comment]
This package works only as Card. You may implement it and make a new package :)

**Comment by cloudstudio** [comment]
I know, but we can change the position with JS like this photo with 4 JS lines.

Okey, you are not open to PR :P
