### ISSUE TITLE
Is it possible to select first filter on page load?

### ISSUE THREAD

**Issue by 4unkur** [awesome-nova/filter-card#4]
For example I have a resource with statuses: Active, Inactive.  
When I open resource index page, is it possible so Active filter will be activated automatically.  
Currently user have to manually click on the first filter card

**Comment by dkulyk** [comment]
https://nova.laravel.com/docs/2.0/filters/defining-filters.html#filter-default-values

**Comment by 4unkur** [comment]
Thanks @dkulyk !
